---
- hosts: all
  user: aagrawa8

  tasks:
   - name: Upgrade packages
     sudo: true
     yum: name=* state=latest 

   - name: Install git
     sudo: true
     yum: name=git state=installed update_cache=true
     
   - name: Install scala
     sudo: true
     yum: name=http://downloads.typesafe.com/scala/2.11.5/scala-2.11.5.rpm state=installed update_cache=true
